version: '3.4'

x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "300m"
    max-file: '3'

networks:
  monitoring: null
volumes:
  prometheus-data: null
  grafana-data: null
services:
  monitoring:
    container_name: tonstatus-monitoring
    build:
      context: .
      dockerfile: Dockerfile
    image: monitoring:latest
    env_file:
      - .env
    restart: unless-stopped
    logging: *default-logging
    networks:
      - monitoring

  prometheus:
    container_name: tonstatus-prometheus
    image: prom/prometheus
    restart: unless-stopped
    logging: *default-logging
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=1y'
      - '--web.enable-lifecycle'
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: tonstatus-grafana
    image: grafana/grafana
    restart: unless-stopped
    logging: *default-logging
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "127.0.0.1:3000:3000"
